METADATA_COLUMNS = [
    "vacancyID",
    "disability_name_Disabled",
    "disability_name_Non-Disabled",
    "disability_name_Prefer not to say",
    "disability_name_Restricted Data",
    "approach_name_50",
    "approach_name_Across government",
    "approach_name_External",
    "approach_name_Internal",
    "approach_name_Pre-release",
    "gender_name_Female",
    "gender_name_Male",
    "gender_name_Other",
    "gender_name_Prefer not to say",
    "gender_name_Restricted Data",
    "ethnicgroup_name_Asian / Asian British",
    "ethnicgroup_name_Black / African / Caribbean / Black British",
    "ethnicgroup_name_Mixed / multiple ethnic groups",
    "ethnicgroup_name_Other ethnic group",
    "ethnicgroup_name_Prefer not to disclose",
    "ethnicgroup_name_Restricted Data",
    "ethnicgroup_name_White",
    "agegroup_name_16-24",
    "agegroup_name_25-29",
    "agegroup_name_30-34",
    "agegroup_name_35-39",
    "agegroup_name_40-44",
    "agegroup_name_45-49",
    "agegroup_name_50-54",
    "agegroup_name_55-59",
    "agegroup_name_60-64",
    "agegroup_name_65+",
    "agegroup_name_Prefer not to disclose",
    "agegroup_name_Restricted Data",
    "failed interview",
    "Offer",
    "Reserve",
    "failed sift",
    "total apps",
    "offered interview",
    "% failed sift",
    "% passed sift",
    "SEB_intermediate",
    "SEB_lower",
    "SEB_professional",
    "SEB_unknown",
    "Unnamed: 0.1",
    "job_title",
    "customer",
    "live_date_latest",
    "min_salary",
    "max_salary",
    "vacancy_report_grade",
    "profession",
    "role_type",
    "language_requirements",
    "licence_requirements",
    "membership_requirements",
    "specific_past_experince_skills_long",
    "qualification_requirements",
    "grid_vacancy_id",
    "ats_vacancy_status",
    "business_area_main",
    "business_area_granular",
    "number_of_jobs_latest",
    "guidance_for_candidate_personal_statement",
    "Application ID",
    "Locs",
    "number_locs",
    "Average_score",
    "Top_skills",
    "vacancy_ref",
    "postcode_master",
    "gor_region",
]
CONTENT_COLUMNS = ["full_job_desc"]
